language: go

go:
    - tip

install:
    - go get code.google.com/p/go.crypto/bcrypt
    - go get github.com/gorilla/mux
    - go get github.com/gorilla/sessions
    - go get github.com/go-sql-driver/mysql
    - go get gopkg.in/mgo.v2

before_script:
    - mysql -e 'create database httpauth_test;'

services:
    - mongodb
